In [22]:
# import library dan data
import pandas as pd
import numpy as np

In [23]:
df = pd.read_csv("Top_1000_Companies_Dataset.csv")
df.head()

,company_name,url,city,state,country,employees,linkedin_url,founded,Industry,GrowjoRanking,...,keywords,LeadInvestors,Accelerator,btype,valuation,total_funding,product_url,indeed_url,growth_percentage,contact_info
0,OpenAI,openai.com,San Francisco,CA,United States,655,http://www.linkedin.com/company/openai,2015.0,AI,1,...,"Artificial Intelligence, Online Gaming, Non Pr...","Thrive, Founders Fund",NaN,NaN,2.900000e+10,$11B,https://www.growjo.com/company/OpenAI,https://www.indeed.com/jobs?q=company%3A(OpenAI),118%,For Contact Direct Phone Numbers and Emails se...
1,Alchemy,alchemy.com,San Francisco,CA,United States,201,http://www.linkedin.com/company/alchemyinc,NaN,Fintech,2,...,NaN,"Lightspeed, Silver Lake",NaN,NaN,1.020000e+10,$564M,https://www.growjo.com/company/Alchemy,https://www.indeed.com/jobs?q=company%3A(Alchemy),134%,For Contact Direct Phone Numbers and Emails se...
2,dbt Labs,getdbt.com,Philadelphia,PA,United States,511,http://www.linkedin.com/company/dbtlabs,2016.0,Analytics,3,...,NaN,Altimeter,NaN,NaN,4.200000e+09,$414.4M,https://www.growjo.com/company/dbt_Labs,https://www.indeed.com/jobs?q=company%3A(dbt L...,76%,For Contact Direct Phone Numbers and Emails se...
3,Wasabi Technologies,wasabi.com,Boston,MA,United States,355,http://www.linkedin.com/company/wasabitechnolo...,2017.0,Cloud,4,...,saas,L2 Point,NaN,NaN,1.100000e+09,$286.2M,https://www.growjo.com/company/Wasabi_Technolo...,https://www.indeed.com/jobs?q=company%3A(Wasab...,60%,For Contact Direct Phone Numbers and Emails se...
4,Whatnot,whatnot.com,Los Angeles,CA,United States,551,http://www.linkedin.com/company/whatnot-inc,2019.0,eCommerce,5,...,NaN,DST Global,NaN,NaN,3.700000e+09,$484.7M,https://www.growjo.com/company/Whatnot,https://www.indeed.com/jobs?q=company%3A(Whatnot),97%,For Contact Direct Phone Numbers and Emails se...

In [24]:
unik = df["city"].unique()
unik

array(['San Francisco', 'Philadelphia', 'Boston', 'Los Angeles', 'Denver',
       'New York', 'Everywhere', 'Wilmington', 'Austin', 'San Diego',
       'London', 'Santa Clara', 'San Mateo', 'Brooklyn', 'Milpitas',
       'Campbell', 'Palo Alto', 'Detroit', 'SAN FRANCISCO', 'Helsinki',
       'Boca Raton', 'Netanya', 'Toronto', 'Greenwich',
       'South Burlington', 'Southern', 'Orlando', 'Burlingame',
       'Santa Monica', 'Redwood City', 'Columbus', 'Scottsdale', 'Miami',
       'Dallas', 'Fresno', "Ra'anana", 'Mountain View', 'Tel Aviv',
       'Irvine', 'Vernier', 'Seattle', 'Torrance', 'Abu Dhabi',
       'Bangalore', 'Oakland', 'Culver City', 'Amsterdam', 'Tampa',
       'Bellevue', 'West End', 'Sydney', 'Jersey City', 'Santa Barbara',
       'Las Vegas', 'Brisbane', 'Nashville', 'Croix', 'Stamford',
       'Arlington', 'Zurich', 'Lehi', 'Singapore', 'Burlington', 'Tempe',
       'Oulu', 'Baltimore', 'Lincoln', 'Los Altos', 'Waterloo',
       'Fort Lee', 'Berkeley', 'Petah Tikva', nan, 'Mahe', 'Brookline',
       'Venice', 'Boulder', 'Mumbai', 'North Richland Hills',
       'Lincolnshire', 'Chennai', 'Vienna', 'Washington',
       'Royal Palm Beach', 'St. Louis', 'Jacksonville', 'Munich',
       'Vancouver', 'New Delhi', 'Sevilla', 'Pune', 'Ghent', 'Stockholm',
       'Reno', 'Giza', 'Karachi', 'Dyersburg', 'Paris', 'Dublin',
       'Frankfurt am Main', 'Gurgaon', 'Fremont', 'Cologne', 'Berlin',
       'Ciudad de MÃƒÂ©xico', 'Calgary', 'Harjumaa', 'Chattanooga',
       'Morrisville', 'Cambridge', 'Beijing', 'Panama City',
       'Serilingampally Mandal', 'Lewisburg', 'Lakeland North', 'Oslo',
       'Atlanta', 'Loveland', 'Charlotte', 'Burnaby', 'Port Washington',
       'Chicago', 'Menlo Park', 'Louisville', 'Mexico City', 'Sunnyvale',
       'Yehud', 'Fairfield', 'Milano', 'Grove City', 'Kilkenny',
       'Chapinero', 'Phoenix', 'Milton Keynes', 'San Leandro', 'Chemnitz',
       'Navi Mumbai', 'Northbrook', 'Indio', 'Vaduz', 'Spokane Valley',
       'Dover', 'Beverly Hills', 'Santa Catarina', 'Blue Ash', 'Chandler',
       'Madrid', 'Bruchsal', 'London-UK', 'Lawrenceville', 'Indianapolis',
       'Bloomfield Hills', 'Mississauga', 'Salt Lake City', 'Brentwood',
       'Durham', 'Indore', 'Westport', 'Jakarta', 'Irving', 'Wolf Trap',
       'Monterrey', 'Nairobi', 'Key Largo', 'Draper', 'Lenexa', 'Herndon',
       'Greenwood Village', 'New delhi', 'Narbonne', 'Bromsgrove',
       'Fayetteville', 'Puri', 'Ann Arbor', 'Seattle area',
       'Raleigh-Durham', 'Livermore', 'Pearland', 'Pasadena',
       'Round Rock', 'Quito', 'Ottawa', 'Sandy Springs', 'Minneapolis',
       'Seoul', 'Apache Junction', 'Franklin Lakes', 'Clinton Township ',
       'Los Altos Hills', 'Hsinchu', 'NOIDA', 'Van Nuys', 'Hollister',
       'Thousand Oaks', 'BVI', 'Scoresby', 'Delhi', 'Johannesburg',
       'Cleveland', 'Waltham', 'Hanover', 'Jefferson', 'Delanco',
       'Plantation', 'Traverse City', 'Lucknow', 'Victoria',
       'St. Louis Park', 'Cabazon', 'Mill Valley', 'Walnut Creek',
       'Greensboro', 'Saratoga', 'Freeport', 'Winter Park',
       'Ballenger Creek', 'Plymouth', 'Kansas City', 'San Jose',
       'Santa Ana', 'Kuwait City', 'El Segundo', 'Sotto', 'Richmond',
       'Schenectady', 'Westerville', 'Elgin', 'Alexandria', 'Rosslyn ',
       'Bengaluru', 'Hyderabad', 'Arendal', 'Vilnius', 'Henderson',
       'Portland', 'Manhattan', 'South Jordan', 'Virginia Beach',
       'Newport Beach', 'Davis', 'Windhoek', 'Bangkok', 'Alameda',
       'Sacramento', 'Coral Springs', 'Brea', 'Buffalo', 'Orem',
       'St Louis', 'Mansfield', 'Oakdale', 'Newton', 'Cincinnati',
       'Silver Spring', 'Alpharetta', 'The Hague', 'Sierre', 'Gurugram',
       'Houston', 'Baton Rouge', 'Fort Lauderdale', 'TEMPE',
       'Farrington Gurney', 'Limassol', 'Gaithersburg', 'New Territories',
       'Costa Mesa', 'Hayward', 'Somerville', 'Worcester', 'Bartlett',
       'Montreal', 'American Fork', 'Redmond', 'Charleston', 'Emeryville',
       'Pleasanton', 'Leawood', 'NEW YORK', 'King of Prussia', 'Perth',
       'Falconer', 'Chicago ', 'Caesarea', 'Milwaukee', 'Bowie',
       'Winnipeg', 'Cracow', 'Albany', 'Hawthorne', 'Gainesville',
       'Elkhart', 'Rockville', 'Nashua', 'Cape Town', 'Pittsburgh',
       'Ã„Â°stanbul', 'Milton', 'Sao Paulo', 'Franklin', 'California ',
       'Sherman Oaks', 'Sectorul 1', 'Marina Del Rey', 'Mechanicsburg',
       'Roseville', 'Chesterfield', 'Uxbridge', 'Coppell',
       'Winston-Salem', 'Altrincham', 'Oakwood Village',
       'South San Francisco', 'Yosemite Lakes', 'Shaker Heights',
       'Sausalito', 'Carson City', 'Hoboken', 'NANTES', 'Enid',
       'Framingham', 'Agoura Hills', 'Natick', 'Carmel', 'San Ramon',
       'Monrovia', 'Solana Beach', 'Auckland', 'Golden', 'KÃ¸benhavn Ã˜',
       'Knoxville', 'San Clemente', 'Burnsville', 'Toledo', 'Lincolnia',
       'Monument'], dtype=object)

In [25]:
df["city"].nunique()

335

In [26]:
import requests
import json
 
def fetch_wikidata(params):
    url = 'https://www.wikidata.org/w/api.php'
    try:
        return requests.get(url, params=params)
    except:
        return 'There was and error'

In [27]:
query = 'Philadelphia'
 
# Which parameters to use
params = {
        'action': 'wbsearchentities',
        'format': 'json',
        'search': query,
        'language': 'en'
    }
 
# Fetch API
data = fetch_wikidata(params)
 
#show response as JSON
data = data.json()

dt = [data["search"][0]["label"], data["search"][0]["id"], data["search"][0]["description"]]
print(dt)

['Philadelphia', 'Q1345', 'largest city in Pennsylvania, United States']

In [28]:
# import csv

# emptyList = []

# for i in (df["city"].unique()):
#     params = {
#         'action': 'wbsearchentities',
#         'format': 'json',
#         'search': i,
#         'language': 'en'
#     }

#     try:
#         data = fetch_wikidata(params)
#         data = data.json()
#         emptyList.append([data["search"][0]["label"], data["search"][0]["id"], data["search"][0]["description"]])
#     except:
#         print(i)
#         emptyList.append([i, "None", "None"])

# pandasdata = pd.DataFrame(emptyList, columns=['Name', 'id', 'Label'])
# pandasdata.to_csv("has.csv", index=False, sep=',', quoting=csv.QUOTE_MINIMAL)

In [29]:
ta = pd.read_csv("has.csv")

In [30]:
df1 = pd.read_csv("has.csv")

df1.loc[~(df1["Label"].str.contains("city")) & ~(df1["Label"].str.contains("town")) & ~(df1["Label"].str.contains("district"))
        & ~(df1["Label"].str.contains("county")) & ~(df1["Label"].str.contains("municipality")) & ~(df1["Label"].str.contains("commune"))
        & ~(df1["Label"].str.contains("capital")) & ~(df1["Label"].str.contains("sector")) & ~(df1["Label"].str.contains("City"))
        & ~(df1["Label"].str.contains("County")) & ~(df1["Label"].str.contains("island")) & ~(df1["Label"].str.contains("metropolis"))
        & ~(df1["Label"].str.contains("state")) & ~(df1["Label"].str.contains("hamlet")) & ~(df1["Label"].str.contains("village"))
        & ~(df1["Label"].str.contains("region")) & ~(df1["Label"].str.contains("neighborhood")) & ~(df1["Label"].str.contains("place"))
        & ~(df1["Label"].str.contains("Capital")) & ~(df1["Label"].str.contains("suburb"))]

# df1["Label"].str.contains("city")

,Name,id,Label
6,Everywhere,Q5418171,1987 single by Fleetwood Mac
15,Campbell,Q2665383,family name
23,Royal Borough of Greenwich,Q693450,royal borough in the London Region in England
25,Southern,Q1258373,train operating company in the United Kingdom
38,"University of California, Irvine",Q868421,"public research university in Irvine, Californ..."
70,"University of California, Berkeley",Q168756,"public university in Berkeley, California"
72,Southern Min,Q36495,branch of the Min Chinese language
104,Ciudad de MÃƒÂ©xico,None,None
109,University of Cambridge,Q35794,collegiate public research university in Cambr...
132,Phoenix,Q10441,minor constellation in the southern sky
148,London-UK,None,None
159,Irving,None,None
174,Seattle Area Archivists,Q107959275,professional society in United States
175,Raleigh-Durham Triangles,Q17066059,1970â€“71 name of the Durham Bulls baseball team
176,Lawrence Livermore National Laboratory,Q519826,"federal research institute in Livermore, Calif..."
189,212631 Hsinchu,Q42897871,asteroid
194,British Virgin Islands,Q25305,British overseas territory in the Caribbean
195,Scoresby,Q1333078,lunar impact crater
202,Delanco,Q5253121,"train station in Delanco, New Jersey"
222,Ojibwe,Q255872,group of indigenous peoples in North America
239,"University of California, Davis",Q129421,"public university in Davis, California; part o..."
242,avenue,Q7543083,"wide, straight, usually tree-lined road or app..."
249,Mansfield Town F.C.,Q18522,"association football club in Mansfield, England"
251,Isaac Newton,Q935,English mathematician and physicist (1642â€“1727)
270,Bartlett,Q15785662,family name
281,Falconer,Q16390438,family name
285,David Bowie,Q5383,English musician and actor (1947â€“2016)
296,Ã„Â°stanbul,None,None
310,Altrincham F.C.,Q18660,"association football club in Altrincham, England"
311,Oakwood Village,None,None
323,Mount Carmel,Q185318,Mountain in Israel
328,gold,Q208045,color
329,Copenhagen Open,Q299499,tennis tournament
331,Clement I,Q42887,4th Pope of the Catholic Church
335,monument,Q4989906,imposing structure created to commemorate a pe...

In [31]:
duplicateRows = df1[df1.duplicated()]
duplicateRows

              Name       id                                              Label
18   San Francisco      Q62  consolidated city and county in California, Un...
168      New Delhi     Q987                              capital city of India
229      Bangalore    Q1355                           city in Karnataka, India
248      St. Louis   Q38022        independent city in Missouri, United States
257        Gurgaon  Q238508                             City in Haryana, India
261          Tempe   Q51685    city in Maricopa County, Arizona, United States
278  New York City      Q60            most populous city in the United States
282        Chicago    Q1297  city and county seat of Cook County, Illinois,...

In [32]:
unik2 = ta["Name"].unique()

In [33]:
for i in unik:
    if i not in unik2:
        print(i)

New York
SAN FRANCISCO
Greenwich
Irvine
Arlington
Zurich
Berkeley
nan
Mahe
Washington
Sevilla
Frankfurt am Main
Harjumaa
Cambridge
Milano
Kilkenny
New delhi
Seattle area
Raleigh-Durham
Livermore
Clinton Township
Hsinchu
NOIDA
BVI
Jefferson
Plantation
Sotto
Rosslyn
Bengaluru
Davis
Alameda
St Louis
Mansfield
Newton
Gurugram
TEMPE
NEW YORK
Chicago
Caesarea
Bowie
Cracow
Sao Paulo
Franklin
California
Sectorul 1
Marina Del Rey
Altrincham
NANTES
Carmel
Golden
KÃ¸benhavn Ã˜
San Clemente
Monument

###### Try splitting DF

In [34]:
df = pd.read_csv("Top_1000_Companies_Dataset.csv")
df.head()

,company_name,url,city,state,country,employees,linkedin_url,founded,Industry,GrowjoRanking,...,keywords,LeadInvestors,Accelerator,btype,valuation,total_funding,product_url,indeed_url,growth_percentage,contact_info
0,OpenAI,openai.com,San Francisco,CA,United States,655,http://www.linkedin.com/company/openai,2015.0,AI,1,...,"Artificial Intelligence, Online Gaming, Non Pr...","Thrive, Founders Fund",NaN,NaN,2.900000e+10,$11B,https://www.growjo.com/company/OpenAI,https://www.indeed.com/jobs?q=company%3A(OpenAI),118%,For Contact Direct Phone Numbers and Emails se...
1,Alchemy,alchemy.com,San Francisco,CA,United States,201,http://www.linkedin.com/company/alchemyinc,NaN,Fintech,2,...,NaN,"Lightspeed, Silver Lake",NaN,NaN,1.020000e+10,$564M,https://www.growjo.com/company/Alchemy,https://www.indeed.com/jobs?q=company%3A(Alchemy),134%,For Contact Direct Phone Numbers and Emails se...
2,dbt Labs,getdbt.com,Philadelphia,PA,United States,511,http://www.linkedin.com/company/dbtlabs,2016.0,Analytics,3,...,NaN,Altimeter,NaN,NaN,4.200000e+09,$414.4M,https://www.growjo.com/company/dbt_Labs,https://www.indeed.com/jobs?q=company%3A(dbt L...,76%,For Contact Direct Phone Numbers and Emails se...
3,Wasabi Technologies,wasabi.com,Boston,MA,United States,355,http://www.linkedin.com/company/wasabitechnolo...,2017.0,Cloud,4,...,saas,L2 Point,NaN,NaN,1.100000e+09,$286.2M,https://www.growjo.com/company/Wasabi_Technolo...,https://www.indeed.com/jobs?q=company%3A(Wasab...,60%,For Contact Direct Phone Numbers and Emails se...
4,Whatnot,whatnot.com,Los Angeles,CA,United States,551,http://www.linkedin.com/company/whatnot-inc,2019.0,eCommerce,5,...,NaN,DST Global,NaN,NaN,3.700000e+09,$484.7M,https://www.growjo.com/company/Whatnot,https://www.indeed.com/jobs?q=company%3A(Whatnot),97%,For Contact Direct Phone Numbers and Emails se...

In [35]:
import csv

df['LeadInvestors'] = df['LeadInvestors'].str.split(', ')
df = df.explode('LeadInvestors')

df['keywords'] = df['keywords'].str.split(', ')
df = df.explode('keywords')

df.to_csv("new_df.csv", index=False, sep=',', quoting=csv.QUOTE_MINIMAL) 

df.head(15)

,company_name,url,city,state,country,employees,linkedin_url,founded,Industry,GrowjoRanking,...,keywords,LeadInvestors,Accelerator,btype,valuation,total_funding,product_url,indeed_url,growth_percentage,contact_info
0,OpenAI,openai.com,San Francisco,CA,United States,655,http://www.linkedin.com/company/openai,2015.0,AI,1,...,Artificial Intelligence,Thrive,NaN,NaN,2.900000e+10,$11B,https://www.growjo.com/company/OpenAI,https://www.indeed.com/jobs?q=company%3A(OpenAI),118%,For Contact Direct Phone Numbers and Emails se...
0,OpenAI,openai.com,San Francisco,CA,United States,655,http://www.linkedin.com/company/openai,2015.0,AI,1,...,Online Gaming,Thrive,NaN,NaN,2.900000e+10,$11B,https://www.growjo.com/company/OpenAI,https://www.indeed.com/jobs?q=company%3A(OpenAI),118%,For Contact Direct Phone Numbers and Emails se...
0,OpenAI,openai.com,San Francisco,CA,United States,655,http://www.linkedin.com/company/openai,2015.0,AI,1,...,Non Profit,Thrive,NaN,NaN,2.900000e+10,$11B,https://www.growjo.com/company/OpenAI,https://www.indeed.com/jobs?q=company%3A(OpenAI),118%,For Contact Direct Phone Numbers and Emails se...
0,OpenAI,openai.com,San Francisco,CA,United States,655,http://www.linkedin.com/company/openai,2015.0,AI,1,...,Artificial Intelligence,Founders Fund,NaN,NaN,2.900000e+10,$11B,https://www.growjo.com/company/OpenAI,https://www.indeed.com/jobs?q=company%3A(OpenAI),118%,For Contact Direct Phone Numbers and Emails se...
0,OpenAI,openai.com,San Francisco,CA,United States,655,http://www.linkedin.com/company/openai,2015.0,AI,1,...,Online Gaming,Founders Fund,NaN,NaN,2.900000e+10,$11B,https://www.growjo.com/company/OpenAI,https://www.indeed.com/jobs?q=company%3A(OpenAI),118%,For Contact Direct Phone Numbers and Emails se...
0,OpenAI,openai.com,San Francisco,CA,United States,655,http://www.linkedin.com/company/openai,2015.0,AI,1,...,Non Profit,Founders Fund,NaN,NaN,2.900000e+10,$11B,https://www.growjo.com/company/OpenAI,https://www.indeed.com/jobs?q=company%3A(OpenAI),118%,For Contact Direct Phone Numbers and Emails se...
1,Alchemy,alchemy.com,San Francisco,CA,United States,201,http://www.linkedin.com/company/alchemyinc,NaN,Fintech,2,...,NaN,Lightspeed,NaN,NaN,1.020000e+10,$564M,https://www.growjo.com/company/Alchemy,https://www.indeed.com/jobs?q=company%3A(Alchemy),134%,For Contact Direct Phone Numbers and Emails se...
1,Alchemy,alchemy.com,San Francisco,CA,United States,201,http://www.linkedin.com/company/alchemyinc,NaN,Fintech,2,...,NaN,Silver Lake,NaN,NaN,1.020000e+10,$564M,https://www.growjo.com/company/Alchemy,https://www.indeed.com/jobs?q=company%3A(Alchemy),134%,For Contact Direct Phone Numbers and Emails se...
2,dbt Labs,getdbt.com,Philadelphia,PA,United States,511,http://www.linkedin.com/company/dbtlabs,2016.0,Analytics,3,...,NaN,Altimeter,NaN,NaN,4.200000e+09,$414.4M,https://www.growjo.com/company/dbt_Labs,https://www.indeed.com/jobs?q=company%3A(dbt L...,76%,For Contact Direct Phone Numbers and Emails se...
3,Wasabi Technologies,wasabi.com,Boston,MA,United States,355,http://www.linkedin.com/company/wasabitechnolo...,2017.0,Cloud,4,...,saas,L2 Point,NaN,NaN,1.100000e+09,$286.2M,https://www.growjo.com/company/Wasabi_Technolo...,https://www.indeed.com/jobs?q=company%3A(Wasab...,60%,For Contact Direct Phone Numbers and Emails se...
4,Whatnot,whatnot.com,Los Angeles,CA,United States,551,http://www.linkedin.com/company/whatnot-inc,2019.0,eCommerce,5,...,NaN,DST Global,NaN,NaN,3.700000e+09,$484.7M,https://www.growjo.com/company/Whatnot,https://www.indeed.com/jobs?q=company%3A(Whatnot),97%,For Contact Direct Phone Numbers and Emails se...
5,Crusoe Energy Systems,crusoeenergy.com,Denver,CO,United States,201,http://www.linkedin.com/company/crusoe,2018.0,Energy/Oil,6,...,Cloud Computing,Bain Capital Ventures,NaN,NaN,1.750000e+09,$747.5M,https://www.growjo.com/company/Crusoe_Energy_S...,https://www.indeed.com/jobs?q=company%3A(Cruso...,68%,For Contact Direct Phone Numbers and Emails se...
5,Crusoe Energy Systems,crusoeenergy.com,Denver,CO,United States,201,http://www.linkedin.com/company/crusoe,2018.0,Energy/Oil,6,...,Oil and Gas,Bain Capital Ventures,NaN,NaN,1.750000e+09,$747.5M,https://www.growjo.com/company/Crusoe_Energy_S...,https://www.indeed.com/jobs?q=company%3A(Cruso...,68%,For Contact Direct Phone Numbers and Emails se...
5,Crusoe Energy Systems,crusoeenergy.com,Denver,CO,United States,201,http://www.linkedin.com/company/crusoe,2018.0,Energy/Oil,6,...,High Performance Computing,Bain Capital Ventures,NaN,NaN,1.750000e+09,$747.5M,https://www.growjo.com/company/Crusoe_Energy_S...,https://www.indeed.com/jobs?q=company%3A(Cruso...,68%,For Contact Direct Phone Numbers and Emails se...
5,Crusoe Energy Systems,crusoeenergy.com,Denver,CO,United States,201,http://www.linkedin.com/company/crusoe,2018.0,Energy/Oil,6,...,Computation,Bain Capital Ventures,NaN,NaN,1.750000e+09,$747.5M,https://www.growjo.com/company/Crusoe_Energy_S...,https://www.indeed.com/jobs?q=company%3A(Cruso...,68%,For Contact Direct Phone Numbers and Emails se...